/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.view;

import br.com.controller.ClienteController;
import br.com.controller.ConhecimentoController;
import br.com.dto.ClienteDTO;
import br.com.dto.ConhecimentoDTO;
import br.com.view.interfaces.Form;
import br.com.utils.FormatadorData;
import br.com.utils.FormatadorDouble;
import br.com.utils.MostraErro;
import br.com.utils.ValidaData;
import java.awt.event.ActionEvent;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.ToolTipManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cleber
 */
public class FormAtualizarFretePadrao extends javax.swing.JFrame implements Form {

    private boolean mudouView = false;
    ConhecimentoController ccRN = new ConhecimentoController();

    /**
     * Creates new form formAtualizarFretePadrao
     */
    public FormAtualizarFretePadrao() {
        initComponents();
        this.populaCbCliente();
        this.populaForm();
        this.setLocationRelativeTo(null);
        //seta o tempo de exibição do ToolTip para 20 segundos
        ToolTipManager.sharedInstance().setDismissDelay(40000);
        panelDestinatario.setVisible(false);
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setVisible(true);
    }

    @Override
    public void setCnpjDestinatario(String cnpj) {
        this.txtCNPJDestinatario.setText(cnpj);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelForm = new javax.swing.JPanel();
        panelRegras = new javax.swing.JPanel();
        panelAlterarFretePara = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lbValorInicial = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtValorEntrega = new javax.swing.JTextField();
        txtPercentual = new javax.swing.JTextField();
        txtLimite = new javax.swing.JTextField();
        btnSimular = new javax.swing.JButton();
        jPanelPeriodo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dataI = new com.toedter.calendar.JDateChooser();
        dataF = new com.toedter.calendar.JDateChooser();
        cbCliente = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        btnAtualizar = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        ckHabilitaDestinatario = new javax.swing.JCheckBox();
        panelDestinatario = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtCNPJDestinatario = new javax.swing.JTextField();
        btnProcurarDestinatario = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbResultado = new javax.swing.JTable();
        panelDadosSimulacao = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtVlrAnterior = new javax.swing.JTextField();
        txtvlrAtual = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alterar Frete Padrão");
        setAlwaysOnTop(true);

        panelRegras.setBorder(javax.swing.BorderFactory.createTitledBorder("Regras de Atualização de Frete"));
        panelRegras.setPreferredSize(new java.awt.Dimension(323, 73));

        panelAlterarFretePara.setBorder(javax.swing.BorderFactory.createTitledBorder("Alterar Frete Para"));
        panelAlterarFretePara.setPreferredSize(new java.awt.Dimension(338, 108));

        jLabel6.setText("Valor por Entrega");

        lbValorInicial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbValorInicial.setText("<html>\n% Sobre Valor<br>\n Transportado\n</html>");
        lbValorInicial.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("<html>\nValor Limite Para\n<br>\nConbrança por Entrega\n</html>");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        txtValorEntrega.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtValorEntregaKeyPressed(evt);
            }
        });

        txtPercentual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPercentualKeyPressed(evt);
            }
        });

        txtLimite.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLimiteKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panelAlterarFreteParaLayout = new javax.swing.GroupLayout(panelAlterarFretePara);
        panelAlterarFretePara.setLayout(panelAlterarFreteParaLayout);
        panelAlterarFreteParaLayout.setHorizontalGroup(
            panelAlterarFreteParaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlterarFreteParaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAlterarFreteParaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtValorEntrega))
                .addGap(18, 18, 18)
                .addGroup(panelAlterarFreteParaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbValorInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelAlterarFreteParaLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtPercentual)))
                .addGap(18, 18, 18)
                .addGroup(panelAlterarFreteParaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addComponent(txtLimite))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAlterarFreteParaLayout.setVerticalGroup(
            panelAlterarFreteParaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlterarFreteParaLayout.createSequentialGroup()
                .addGap(0, 30, Short.MAX_VALUE)
                .addGroup(panelAlterarFreteParaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbValorInicial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAlterarFreteParaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValorEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPercentual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLimite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnSimular.setText("Simular");
        btnSimular.setToolTipText("Simula a atualização do Frete.");
        btnSimular.setMaximumSize(new java.awt.Dimension(85, 28));
        btnSimular.setMinimumSize(new java.awt.Dimension(85, 28));
        btnSimular.setPreferredSize(new java.awt.Dimension(85, 28));
        btnSimular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimularActionPerformed(evt);
            }
        });

        jPanelPeriodo.setBorder(javax.swing.BorderFactory.createTitledBorder("Período"));

        jLabel3.setText("Data Final:");

        jLabel2.setText("Data Incial:");

        dataI.setToolTipText("Data Inicial");
        dataI.setMaxSelectableDate(new java.util.Date(253370775707000L));
        dataI.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dataIPropertyChange(evt);
            }
        });

        dataF.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dataFPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanelPeriodoLayout = new javax.swing.GroupLayout(jPanelPeriodo);
        jPanelPeriodo.setLayout(jPanelPeriodoLayout);
        jPanelPeriodoLayout.setHorizontalGroup(
            jPanelPeriodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPeriodoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataI, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataF, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanelPeriodoLayout.setVerticalGroup(
            jPanelPeriodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPeriodoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPeriodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPeriodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dataF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dataI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPeriodoLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPeriodoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap())))
        );

        cbCliente.setToolTipText("Selecione o Cliente");
        cbCliente.setAutoscrolls(true);
        cbCliente.setName("cbCliente"); // NOI18N
        cbCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbClienteActionPerformed(evt);
            }
        });

        jLabel1.setText("Cliente:");

        btnAtualizar.setText("Atualizar");
        btnAtualizar.setToolTipText("Executa atualização do valor de Frete.");
        btnAtualizar.setEnabled(false);
        btnAtualizar.setMaximumSize(new java.awt.Dimension(85, 28));
        btnAtualizar.setMinimumSize(new java.awt.Dimension(85, 28));
        btnAtualizar.setPreferredSize(new java.awt.Dimension(85, 28));
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.setToolTipText("Pesquisar conhecimentos no período.");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        ckHabilitaDestinatario.setText("Por Destinatário");
        ckHabilitaDestinatario.setToolTipText("Marque está caixa caso queira atualizar o frete de Destinatários especificos.");
        ckHabilitaDestinatario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckHabilitaDestinatarioActionPerformed(evt);
            }
        });

        panelDestinatario.setBorder(javax.swing.BorderFactory.createTitledBorder("Destinatário"));
        panelDestinatario.setToolTipText("");

        jLabel8.setText("CNPJ");

        txtCNPJDestinatario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCNPJDestinatarioKeyPressed(evt);
            }
        });

        btnProcurarDestinatario.setText("Procurar");
        btnProcurarDestinatario.setToolTipText("Pesquisar conhecimentos no período.");
        btnProcurarDestinatario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcurarDestinatarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDestinatarioLayout = new javax.swing.GroupLayout(panelDestinatario);
        panelDestinatario.setLayout(panelDestinatarioLayout);
        panelDestinatarioLayout.setHorizontalGroup(
            panelDestinatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDestinatarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCNPJDestinatario, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnProcurarDestinatario)
                .addContainerGap())
        );
        panelDestinatarioLayout.setVerticalGroup(
            panelDestinatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDestinatarioLayout.createSequentialGroup()
                .addGroup(panelDestinatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCNPJDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProcurarDestinatario))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelRegrasLayout = new javax.swing.GroupLayout(panelRegras);
        panelRegras.setLayout(panelRegrasLayout);
        panelRegrasLayout.setHorizontalGroup(
            panelRegrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegrasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRegrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRegrasLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ckHabilitaDestinatario))
                    .addGroup(panelRegrasLayout.createSequentialGroup()
                        .addGroup(panelRegrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelAlterarFretePara, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                            .addComponent(jPanelPeriodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelRegrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPesquisar)
                            .addComponent(btnSimular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        panelRegrasLayout.setVerticalGroup(
            panelRegrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegrasLayout.createSequentialGroup()
                .addGroup(panelRegrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckHabilitaDestinatario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(panelRegrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelDestinatario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelPeriodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(panelRegrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRegrasLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelAlterarFretePara, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegrasLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSimular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        tbResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod.", "Cliente", "Destinatario", "Data", "Vlr. Notas", "Vlr. Frete", "Novo Frete", "Vai Alterar", "Foi Alterado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbResultado);
        if (tbResultado.getColumnModel().getColumnCount() > 0) {
            tbResultado.getColumnModel().getColumn(0).setMinWidth(70);
            tbResultado.getColumnModel().getColumn(0).setPreferredWidth(70);
            tbResultado.getColumnModel().getColumn(0).setMaxWidth(70);
            tbResultado.getColumnModel().getColumn(1).setMinWidth(300);
            tbResultado.getColumnModel().getColumn(1).setPreferredWidth(300);
            tbResultado.getColumnModel().getColumn(1).setMaxWidth(700);
            tbResultado.getColumnModel().getColumn(2).setResizable(false);
            tbResultado.getColumnModel().getColumn(2).setPreferredWidth(300);
            tbResultado.getColumnModel().getColumn(3).setResizable(false);
            tbResultado.getColumnModel().getColumn(4).setResizable(false);
            tbResultado.getColumnModel().getColumn(5).setResizable(false);
            tbResultado.getColumnModel().getColumn(6).setResizable(false);
            tbResultado.getColumnModel().getColumn(7).setResizable(false);
            tbResultado.getColumnModel().getColumn(8).setResizable(false);
        }

        panelDadosSimulacao.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado da Simulação"));

        jLabel4.setFont(new java.awt.Font("sansserif", 3, 12)); // NOI18N
        jLabel4.setText("Total Anterior");

        txtVlrAnterior.setEditable(false);
        txtVlrAnterior.setToolTipText("Total dor Frete Antes da Simulação.");

        txtvlrAtual.setEditable(false);
        txtvlrAtual.setToolTipText("Total do Frete Simulado.");

        jLabel7.setFont(new java.awt.Font("sansserif", 3, 12)); // NOI18N
        jLabel7.setText("Total Atual");

        javax.swing.GroupLayout panelDadosSimulacaoLayout = new javax.swing.GroupLayout(panelDadosSimulacao);
        panelDadosSimulacao.setLayout(panelDadosSimulacaoLayout);
        panelDadosSimulacaoLayout.setHorizontalGroup(
            panelDadosSimulacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDadosSimulacaoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelDadosSimulacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDadosSimulacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtVlrAnterior)
                    .addComponent(txtvlrAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        panelDadosSimulacaoLayout.setVerticalGroup(
            panelDadosSimulacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDadosSimulacaoLayout.createSequentialGroup()
                .addGroup(panelDadosSimulacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVlrAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDadosSimulacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtvlrAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)))
        );

        javax.swing.GroupLayout panelFormLayout = new javax.swing.GroupLayout(panelForm);
        panelForm.setLayout(panelFormLayout);
        panelFormLayout.setHorizontalGroup(
            panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFormLayout.createSequentialGroup()
                        .addComponent(panelRegras, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelDadosSimulacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))
                    .addGroup(panelFormLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        panelFormLayout.setVerticalGroup(
            panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormLayout.createSequentialGroup()
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelRegras, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelFormLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelDadosSimulacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimularActionPerformed

        this.ccRN = new ConhecimentoController();
        try {
            this.simularAtualizacao(dataI.getDate(), dataF.getDate());
            this.habilitarBtnAtualizar(true);
        } catch (Exception ex) {
            MostraErro.show(this, ex);
        }
    }//GEN-LAST:event_btnSimularActionPerformed

    private void dataIPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dataIPropertyChange
        mudouView = true;
        habilitarBtnAtualizar(false);
    }//GEN-LAST:event_dataIPropertyChange

    private void dataFPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dataFPropertyChange
        mudouView = true;
        habilitarBtnAtualizar(false);
    }//GEN-LAST:event_dataFPropertyChange

    private void cbClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbClienteActionPerformed
        mudouView = true;
        habilitarBtnAtualizar(false);
        populaForm();
    }//GEN-LAST:event_cbClienteActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed

        try {
            this.populaTabela(this.atualizarFrete());
        } catch (Exception e) {
            MostraErro.show(this, e);
        }

        //Seta o botao atualizar disable. Deve estar desabalitado para garantir
        //que o usuario sempre clique primeiro em simular. Isto garante que a
        //variavel ccRN sempre esteja populada com o ClienteDTO VIEW. Caso
        //contrario se o usuario alterar o ClienteDTO na VIEW e clicar em
        //atualizar, o modelo estára com dados diferentes da VIEW. Fazendo com
        //que a alteração do frete seja refletida no Cliente errado.
        btnAtualizar.setEnabled(false);
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        try {
            this.ccRN = new ConhecimentoController();
            if (!panelDestinatario.isVisible() || txtCNPJDestinatario.getText().isEmpty()) {
                this.pesquisarConhecimentos(dataI.getDate(), dataF.getDate());
            } else {
                this.pesquisarConhecimentosDestinatario(dataI.getDate(), dataF.getDate(), txtCNPJDestinatario.getText());
            }

        } catch (Exception e) {
            MostraErro.show(this, e);
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void ckHabilitaDestinatarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckHabilitaDestinatarioActionPerformed
        habilitaPanelDestinatario(evt);
        mudouView = true;
        habilitarBtnAtualizar(false);
    }//GEN-LAST:event_ckHabilitaDestinatarioActionPerformed

    private void txtCNPJDestinatarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCNPJDestinatarioKeyPressed
        mudouView = true;
        habilitarBtnAtualizar(false);
    }//GEN-LAST:event_txtCNPJDestinatarioKeyPressed

    private void btnProcurarDestinatarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcurarDestinatarioActionPerformed

        mudouView = true;
        habilitarBtnAtualizar(false);

        FormConsultaDestinatario formListaDestinatario = new FormConsultaDestinatario(this);
        this.txtCNPJDestinatario.setText(formListaDestinatario.getCnpj());
    }//GEN-LAST:event_btnProcurarDestinatarioActionPerformed

    private void txtValorEntregaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorEntregaKeyPressed
        habilitaBtnAtualizar(false);
        mudouView = true;
    }//GEN-LAST:event_txtValorEntregaKeyPressed

    private void txtPercentualKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPercentualKeyPressed
        habilitaBtnAtualizar(false);
        mudouView = true;
    }//GEN-LAST:event_txtPercentualKeyPressed

    private void txtLimiteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLimiteKeyPressed
        habilitaBtnAtualizar(false);
        mudouView = true;
    }//GEN-LAST:event_txtLimiteKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAtualizarFretePadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAtualizarFretePadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAtualizarFretePadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAtualizarFretePadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAtualizarFretePadrao().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnProcurarDestinatario;
    private javax.swing.JButton btnSimular;
    private javax.swing.JComboBox cbCliente;
    private javax.swing.JCheckBox ckHabilitaDestinatario;
    private com.toedter.calendar.JDateChooser dataF;
    private com.toedter.calendar.JDateChooser dataI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanelPeriodo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbValorInicial;
    private javax.swing.JPanel panelAlterarFretePara;
    private javax.swing.JPanel panelDadosSimulacao;
    private javax.swing.JPanel panelDestinatario;
    private javax.swing.JPanel panelForm;
    private javax.swing.JPanel panelRegras;
    private javax.swing.JTable tbResultado;
    private javax.swing.JTextField txtCNPJDestinatario;
    private javax.swing.JTextField txtLimite;
    private javax.swing.JTextField txtPercentual;
    private javax.swing.JTextField txtValorEntrega;
    private javax.swing.JTextField txtVlrAnterior;
    private javax.swing.JTextField txtvlrAtual;
    // End of variables declaration//GEN-END:variables

    //####################################
    // Inicio do Codigo personalizado
    //####################################
    private void populaCbCliente() {

        ClienteController clienteRN = new ClienteController();
        try {
            List<ClienteDTO> clientes = clienteRN.getClientes();
            DefaultComboBoxModel model = new DefaultComboBoxModel(clientes.toArray());

            cbCliente.setModel(model);
        } catch (Exception ex) {
            MostraErro.show(this, ex);
        }
    }

    private void habilitarBtnAtualizar(boolean b) {
        btnAtualizar.setEnabled(b);
    }

    private boolean validaCampos() throws Exception {
        boolean ok = true;

        ValidaData.validar(dataI.getDate(), dataF.getDate());

        if (panelDestinatario.isVisible() && txtCNPJDestinatario.getText().isEmpty()) {
            showWarning("Informe o CNPJ do destinatário ou \n"
                    + "clique no botão procurar para seleceionar um.");
            ok = false;
        }
        if (cbCliente.getSelectedIndex() < 0) {
            showWarning("Selecione um cliente.");
            ok = false;

        }
        if (txtValorEntrega.getText().isEmpty()) {
            showWarning("Preencha o campo Valor por Entrega.");
            ok = false;
        }
        if (txtPercentual.getText().isEmpty()) {
            showWarning("Preencha o campo % Sobre Valor Transportado.");
            ok = false;
        }

        if (txtLimite.getText().isEmpty()) {
            showWarning("Preencha o campo Valor limite para cobrança por entrega.");
            ok = false;
        }
        return ok;
    }

    private void showWarning(String msg) {
        JOptionPane.showMessageDialog(this, msg, "Atenção", JOptionPane.WARNING_MESSAGE);
    }

    private void populaTabela(List<ConhecimentoDTO> conhecimentos) throws Exception {
        DefaultTableModel model = (DefaultTableModel) tbResultado.getModel();

        if (conhecimentos == null || conhecimentos.size() < 1) {
            model.setRowCount(0);
            JOptionPane.showMessageDialog(this, "Nehum registro foi localizado.", "Aviso",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {

            double totalAnterior = 0;
            double totalAtual = 0;
            model.setRowCount(conhecimentos.size());

            for (int i = 0; i < conhecimentos.size(); i++) {
                model.setValueAt(conhecimentos.get(i).getId(), i, 0);
                model.setValueAt(conhecimentos.get(i).getCliente().getNome(), i, 1);
                model.setValueAt(conhecimentos.get(i).getDestinatario().getNome(), i, 2);
                model.setValueAt(FormatadorData.toString(conhecimentos.get(i).getDataCC()), i, 3);
                model.setValueAt(FormatadorDouble.toString(conhecimentos.get(i).getVlCC()), i, 4);
                model.setValueAt(FormatadorDouble.toString(conhecimentos.get(i).getVlFrete()), i, 5);
                model.setValueAt(FormatadorDouble.toString(conhecimentos.get(i).getNovoFrete()), i, 6);
                model.setValueAt(conhecimentos.get(i).isVaiAlterar(), i, 7);
                model.setValueAt(conhecimentos.get(i).isAlterouFrete(), i, 8);


                totalAnterior += conhecimentos.get(i).getVlFrete();
                totalAtual += conhecimentos.get(i).getNovoFrete();
            }

            txtVlrAnterior.setText(FormatadorDouble.toString(totalAnterior));
            txtvlrAtual.setText(FormatadorDouble.toString(totalAtual));
        }
    }

    private void habilitaPanelDestinatario(ActionEvent evt) {
        if (panelDestinatario.isVisible()) {
            panelDestinatario.setVisible(false);
        } else {
            panelDestinatario.setVisible(true);
        }
    }

    private void habilitaBtnAtualizar(boolean b) {
        btnAtualizar.setEnabled(b);
    }

    //Simula a atualização de frete
    private void simularAtualizacao(Date inicio, Date fim) throws Exception {
        List<ConhecimentoDTO> conhecimentos = null;

        if (validaCampos()) {
            ccRN.getConhecimento().setCliente((ClienteDTO) cbCliente.getSelectedItem());

            //se o panelDestinatario estiver habilitado chama o procedimento 
            //correspondente para atualziar o frete por destinatario
            if (panelDestinatario.isVisible()) {
                conhecimentos = ccRN.simularFretePadrao(inicio, fim, txtValorEntrega.getText(),
                        txtLimite.getText(), txtPercentual.getText(), txtCNPJDestinatario.getText());

                //se panel destinatario nao estiver habilitado
                //havalia criterios de atualização sem destinatario
            } else {

                conhecimentos = ccRN.simularFretePadrao(inicio, fim, txtValorEntrega.getText(),
                        txtLimite.getText(), txtPercentual.getText(), null);
            }
        } else {
            throw new Exception("Impossível determinar a regra para"
                    + "Atualização do Frete. \n"
                    + "Verifique se todos as criterios foram preenchidos "
                    + "e tente novamente. \n"
                    + "Se o erro persistir contate o suporte informando o problema.");
        }

        this.populaTabela(conhecimentos);
    }

    //Atualiza o frete
    private List<ConhecimentoDTO> atualizarFrete() throws Exception {
        //se paneldestinatario estiver habilitado retorna list com destinatarios informados
        //se não retorna list com todos os destinatarios
        if (panelDestinatario.isVisible()) {
            return ccRN.atualizarFrete(dataI.getDate(), dataF.getDate(), txtCNPJDestinatario.getText());
        } else {
            return ccRN.atualizarFrete(dataI.getDate(), dataF.getDate());
        }
    }

    private void pesquisarConhecimentos(Date inicio, Date fim) throws Exception {
        if (ValidaData.validar(inicio, fim)) {

            ccRN.getConhecimento().setCliente((ClienteDTO) cbCliente.getSelectedItem());
            populaTabela(ccRN.getConhecimentos(inicio, fim));
        }
    }

    private void pesquisarConhecimentosDestinatario(Date inicio, Date fim, String cnpjDestinatario) throws Exception {
        if (ValidaData.validar(inicio, fim)) {

            ccRN.getConhecimento().setCliente((ClienteDTO) cbCliente.getSelectedItem());
            populaTabela(ccRN.getConhecimentos(inicio, fim, cnpjDestinatario));
        }
    }

    private void populaForm() {
        ClienteDTO cliente = (ClienteDTO) cbCliente.getSelectedItem();
        txtLimite.setText(FormatadorDouble.toString(cliente.getLimite()));
        String strPerncetual = ""+ (cliente.getPercentual());
        strPerncetual = strPerncetual.replace(".", ",");
        txtPercentual.setText(strPerncetual);
        txtValorEntrega.setText(FormatadorDouble.toString(cliente.getFixo()));
    }
}
